apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: netobserv-1-8-0-fbc-4-17-5
  namespace: ocp-network-observab-tenant
  labels:
    release.appstudio.openshift.io/author: 'jtakvori'
spec:
  releasePlan: netobserv-fbc-v4-17
  snapshot: fbc-v4-17-ksrjr
