apiVersion: appstudio.redhat.com/v1alpha1
kind: Release
metadata:
  name: release-netobserv-1-9-0-2
  namespace: ocp-network-observab-tenant
  labels:
    release.appstudio.openshift.io/author: 'jtakvori'
spec:
  releasePlan: netobserv-ystream
  snapshot: netobserv-ystream-sj9tp
  data:
    releaseNotes:
      type: RHSA
      cves:
        - key: CVE-2025-26791
          component: network-observability-console-plugin-ystream
